# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Docker file ci

on:
  push:
    branches:
      - main

jobs:
  docker-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: docker build image
        run: "docker build -t meetchhatrala789/nodeapp:${GITHUB_SHA::4} ./my-react-app"
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN_DOCKER }}
      - name: push docker image
        run: "docker push meetchhatrala789/nodeapp:${GITHUB_SHA::4}" 

      - name: Update deployment.yaml with new tag
        run: |
          TAG=${{ GITHUB_SHA::4 }}
          sed -i "s|TAG_PLACEHOLDER|$TAG|g" k8s/deployment.yaml 
      
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "
          git add k8s/deployment.yaml
          git commit -m "Update deployment.yaml with new image tag"
          git push origin main
          


    
